# Generated by Django 3.2.8 on 2021-10-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('hobby', models.CharField(max_length=50)),
                ('talent', models.CharField(max_length=50)),
                ('born', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
            ],
        ),
    ]
