# Generated by Django 3.2.8 on 2021-10-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_introductions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='born',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='talent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(max_length=100),
        ),
    ]
