# Generated by Django 3.2.8 on 2021-10-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_introductions', '0002_auto_20211026_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_follow_user', to='self_introductions.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_follow_user', to='self_introductions.user')),
            ],
        ),
    ]
